### ISSUE TITLE
Can you provide a training log for the ml-100k data?

### ISSUE THREAD

**Issue by HikaruSama233** [THUIR/ACCM#1]
Hi there,

I tried to training your model using your data and default settings, but the training process stopped within 100 epochs. The result was bad.

Could you please provide a training log for a glimpse?

Thanks.

**Comment by Shuriken13** [comment]
Hello, what's your command? I just run the default `python CSACCM.py --warm_ratio 0.9` again and I think the final results is ok. This is the log.
[log.txt](https://github.com/THUIR/ACCM/files/2553044/log.txt)

**Comment by HikaruSama233** [comment]
My result is similar to yours. Thanks.
